"""store wound image in database

Revision ID: ef8c54dcb921
Revises: a29872614fe4
Create Date: 2026-08-05 15:52:01.089289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef8c54dcb921'
down_revision: Union[str, Sequence[str], None] = 'a29872614fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wound_images', sa.Column('image_bytes', sa.LargeBinary(), nullable=False))
    op.drop_column('wound_images', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wound_images', sa.Column('image_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('wound_images', 'image_bytes')
    # ### end Alembic commands ###
